---
output: 
  pdf_document:
    pandoc_args: [
      "-V", "classoption=twocolumn"
    ]
    toc: yes 
    fig_caption: yes
    latex_engine: xelatex
bibliography: bibliography.bib
mainfont: "Arial"
csl: deutsches-archaologisches-institut.csl
---

# Einleitung und Kontextualisierung

Lewis R. Binfords umstrittenes Spätwerk *Constructing Frames of Reference* ist eines der wichtigsten Standardwerke der New Archaeology. Es versteht sich selbst als Methodikstudie zur induktiven Ableitung allgemeiner Regeln menschlichen Verhaltens aus ethnographischen Umwelt- und Sozialdatensätzen, erarbeitet aber am Fallbeispiel eines Datensatzes zu Jäger- und Sammlergruppen gleichermaßen inhaltlich relevante Ergebnisse. 

Binford fasst seine methodischen Ambitionen folgendermaßen zusammen:

> I cannot emphasize strongly enough, that the major problem this book addresses is *the development of a method for productively using ethnographic data in the servive of archaeological goals*. 
> [...] 
> This book is unapologetically written from a scientific perspective. It is largely an exercise in inductive reasoning, in that it asks questions regarding the character of the world of organized variability among ethnographically documented hunter-gatherer groups.
> [...]
> And, since one of the goals of this book is to explain variability among hunter-gatherers, the explanatory theory that I have developed is available for archaeologists to use deductively by reasoning to or simulating changing conditions and thereby providing patterns of change that can be expected to occur in the archaeological record at specific locations.
>  
> -- @binford_constructing_2001, 2-3.

Die systematische Suche nach übergeordneten, wiederkehrenden Strukturen in der Mensch-Umwelt und Mensch-Mensch Beziehung ist eines der wesentlichen Themen des Buches. Die Komplexität dieser Aufgabe erklärt seinen bemerkenswerten Umfang und den dennoch teilweise fragmenthaften Charakter. Binford konstruiert allgemeine Lehrsätze, die für alle Jäger- und Sammlergruppen Gültigkeit beanspruchen. Erarbeitet auf Grundlage eines begrenzten Datensatzes und eines limitierten, analytischen Methodensets sind diese Axiome, qualitative und quantitative Thesen wissenschaftliche Aussagen. Die ihnen zugrundeliegenden Analysen sollten reproduzierbar und falsifizierbar sein. Zur Illustration ein Beispiel einer zufällig ausgewählten These, die im zehnten Kapitel formuliert wird:

> Proposition 10.19: As packing increases, groups that are dependent upon aquatic resources should resort to more complex subsistence technology. Increasing complexity in the design of weapons should also be associated with hunter-gatherer groups that are not primarily dependent upon aquatic resources as a function of their more specialized exploitation of a reduced number of high-yield species (see generalizations 10.15 and 10.16).
>  
> -- @binford_constructing_2001, 392.

Hier wird zunächst ein Rahmen definiert ("groups that are dependent upon aquatic resources") und für den Fall eines Veränderungsprozesses ("as packing increases") eine Vorhersage ("should resort to more complex subsistence technology") getroffen, die dann noch weiter kontextualisiert und präzisiert wird.  
 
Da sowohl die Daten als auch eine -- unterschiedlich ausführliche -- Beschreibung des Methodenset publiziert sind, die der Entwicklung dieser und aller anderen Aussagen in *Constructing Frames of Reference* zugrunde liegen, sollte es möglich sein, ...

1. ... auf Grundlage der selben Daten unter Anwendung der selben Methode zu den gleichen Aussagen zu kommen.

2. ... Aussagen mit anderen Daten und anderen Methoden zu rekonstruieren und gegebenenfalls durch verbesserte Aussagen zu ersetzen.

Der vorliegenden Aufsatz dient auch dazu, Binfords wissenschaftlichen Selbstanspruch zu prüfen. Wie gut ist das Buch für einen zeitgemäßen Reproducible Research Workflow zugänglich? Gleichzeitig muss der Schwerpunkt dieser Arbeit ein didaktischer sein: Ich werde den Umgang mit Grundlagen des wissenschaftlichen Arbeitens üben und -- im Kontext des Hauptseminars -- meine Methodenkompetenz zur Modelleinpassung mittels Regressionsanalyse^[@nakoinz_modelling_2016, 87-105.] ausbauen.  

Vor diesem Hintergrund möchte ich weder versuchen die archäologischen oder archäologietheoretischen Leitgedanken des Buches nachzuzeichnen ^[Für einen kurzen Abriss siehe z.B. @donald_pate_review_2005 oder @browman_constructing_2005], noch seine kontroverse Rezeption aufzugreifen. Kritiker haben Binford neben übermäßigem Naturdeterminismus und Funktionalismus u.a. die Verwendung widersprüchlicher und mangelhaft definierter Neologismen, Rechenfehler und Mängel in der Datenaufnahme bis hin zum Übersehen zentraler Trends vorgeworfen ^[@doi:10.1086/jar.58.3.3631188, @10.2307/4128427]. Die fachtheoretischen Grundlagen des Buches in Kulturökologie und Middle-Range-Theorie gehören in ein ohnehin umstrittenes Feld. Eine Auseinandersetzung mit dem Gesamtwerk ist im zeitlich stark begrenzten Rahmen einer Seminararbeit nicht sinnvoll möglich. Stattdessen möchte ich das Opus höchst selektiv betrachten, berechtigte Kritik vorerst beiseite lassen und mich voll auf einen kleinen Aspekt der explorativen Datenanalyse konzentrieren. Eine erste Abenteuerreise auf den Spuren Binfords, wie sie noch häufig unternommen werden sollte.

> Does it [Binfords *Constructing Frames of Reference*] help us to better suppose hunter-gatherer variability, and to conceptualize variability beyond what we currently know? The answer to the first question is a definite yes, but its generalizations require rigorous testing and replication, the normal scientific process that Binford himself has advocated for four decades.
>  
> @10.2307/4128427, 372.






