---
output: 
  pdf_document:
    toc: yes 
    fig_caption: yes
    latex_engine: xelatex
bibliography: bibliography.bib
mainfont: "Arial"
csl: deutsches-archaologisches-institut.csl
---

# Abschließende Gedanken

Die Ziele, die ich mir für diese Arbeit gesetzt habe, sind weitestgehend erreicht worden. Die Methode der Multiplen Regression habe ich besser verstanden und sinnvoll zur Anwendung bringen können -- obgleich wie zu erwarten Fragen offen geblieben sind. Dabei konnte ich ein Modell formulieren, das nach objektiven, statistischen Kriterien besser zur Erkärung der Variable *area* geeignet ist, als das von Binford vorgeschlagene. Ich erlaube mir jedoch kein Urteil darüber, ob Binfords Modell, in das mittels händischer Auswahl von Variablen bewusst oder unbewusst Fachwissen verarbeitet wurde, dennoch das wissenschaftlich wertvollere ist. Sicher bin ich jedoch, dass sein Vorgehen zur Erstellung des Modells nicht ausreichend dokumentiert ist, um eine exakte Reproduktion zu ermöglichen. Das ist in Anbetracht der Tatsache, dass andere Teile des Buches dahingehend wesentlich besser vorbereitet sind, schade. Auch deswegen lohnt es sich, weiter mit *Constructing Frames of Reference* zu arbeiten und aus dem reichen Schatz an Hypothesen jene herauszuarbeiten, die als solide Grundlage für weitere Forschung dienen können.
