---
title: "Reconstructing Frames of Reference"
subtitle: "Auf den Spuren der Datenanalyse Lewis R. Binfords"
author: "Clemens Schmid"
date: "SS 17"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \usepackage[font=small,labelfont=bf]{caption}
- \usepackage[ngerman]{babel}
output: 
  pdf_document:
    pandoc_args: [
      "-V", "classoption=twocolumn"
    ]
    toc: yes
    toc_depth: 4
    fig_caption: yes
    latex_engine: xelatex
    includes:  
      in_header: preamble-latex.tex
    #keep_tex: yes
geometry: margin=1.5cm
bibliography: bibliography.bib
mainfont: "Arial"
csl: https://www.zotero.org/styles/chicago-author-date-de
---

\fancyhead{}
\fancyfoot{}
\fancyhead[R]{\thepage}
\fancyhead[L]{\leftmark}

<!-- controle space in between paragraphs, figures and tables -->
\parskip 4pt
\setlength{\textfloatsep}{10pt plus 1.0pt minus 2.0pt}

```{r global chunk options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r child = 'binford_introduction.Rmd'}
```


```{r child = 'binford_datasets.Rmd'}
```


```{r child = 'binford_tale_1.Rmd'}
```

\newpage

```{r child = 'binford_end.Rmd'}
```

\section{Literatur}
