# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
script:
  - Rscript -e "devtools::install()"
  - Rscript -e "rmarkdown::render('report/binford_main.Rmd')"
