# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

# take packages from MRAN snapshot
repos:
  MRAN: "https://mran.microsoft.com/snapshot/2017-08-29"

#addons:
#  apt:
#    packages:
#    # install microsoft fonts
#    - ttf-mscorefonts-installer

before_install:
  - tlmgr install babel-german
  #- tlmgr install ngerman
  #- tlmgr install german
    
before_script:
    # install microsoft fonts
    - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    - sudo apt-get install ttf-mscorefonts-installer
    # rebuild font cache
    - sudo fc-cache
    # install tex german language package
    # - sudo apt-get install texlive-lang-german
    
script:
  # install package
  - Rscript -e "devtools::install()"
  # render document
  - Rscript -e "rmarkdown::render('report/binford_main.Rmd')"
